Traceback (most recent call last):
  File "/home/resh/PycharmProjects/pythonProject/mod 5/task4/tests.py", line 30, in test_one_arg_stderr
    raise Exception('Hello stderr.txt')
Exception: Hello stderr.txt
